version: '3'
services:
  app:
    container_name: node16
    build:
      context: .
      dockerfile: prod.Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    depends_on:
          - db
  db:
    container_name: mysql8
    build: ./mysql
    volumes:
      - data:/var/lib/mysql
    env_file: .env
volumes:
  data: